#!/usr/bin/bash

VIM=.vimrc
BOMBADILLO=.bombadillo.ini
MUTT=.muttrc
TMUX=.tmux.conf

cd ~/.dotfiles/
git add $VIM $MUTT $TMUX $BOMBADILLO update-configs
git commit -m "update dotfiles"
git pull origin main
git push origin
